config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  namespace :admin do 
  	resources :posts
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	before_action :find_post, only: %i[show edit update destroy]
	def index
		@posts = Post.all
	end

	def new 
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.save
		redirect_to admin_post_path(@post)
	end
	def show
		
	end
	def edit
	end
	def update
		@post.update(post_params)
		redirect_to admin_post_path(@post)
	end
	def destroy
		@post.destroy
		redirect_to admin_posts_path
	end
	def find_post
		@post = Post.find(params[:id])
	end

	private
	def post_params
		params.require(:post).permit(:title, :content)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :image, :lastname])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/posts/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h1 class="text-center">New post</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-10 mx-auto"></div>
		<%= form_for [:admin, @post] do |f|%>
			</div>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title,class: "form-control" %>
				<div class="form-group">
				<%= f.label :content %>
				<%= f.rich_text_area :content,class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.submit class: "btn btn-primary" %>
				
			</div>
			</div>
</div> <% end %>

app/views/admin/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h1>Edit post</h1>
		</div>
	</div>
	<%= render "form" %>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col text-center">
			<%= link_to "New Post", new_admin_post_path, class: "btn btn-success" %>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<table class="table table-hover table-bordered">
				<tr>
					<th>Title</th>
					<th>Content</th>
					<th>Edit</th>
					<th>Destroy</th>
				</tr>
				<% @posts.each do |post| %>
				<tr>
					<td><%= link_to post.title, admin_post_path(post)  %></td>
					<td><%= post.title %></td>
					<td><%= post.content %></td>
					<td><%= link_to "edit", edit_admin_post_path(post), class: "btn btn-info"%></td>
					<td><%= link_to "destroy", [:admin, post], method: :delete, class: "btn btn-danger" %></td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/admin/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h1>New post</h1>
		</div>
	</div>
	<%= render "form" %>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
	 <div class="row">
	 	<div class="col">
	 		<h1 class="text-center">
	 			<%= @post.title %>
	 			<p>
	 				<%= @post.content %>
	 			</p>
	 		</h1>
	 	</div>
	 </div>

</div>

app/views/home/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="navbar-brand" class="nav-link active" aria-current="page" href=""  ><%= link_to "registration" , new_user_registration_path %>
          </a>
        </li>
        <li class="nav-item">
          <a class="navbar-brand" class="nav-link" href="#"><%= link_to "log in " , new_user_session_path %></a>
        </li>
         <li class="nav-item">
          <a class="navbar-brand"  class="nav-link" href="#" class="text-center"><%= link_to "log out" , destroy_user_session_path, method: :delete %></a>
        </li>
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<h1 class="text-center">Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <%= render "shared/header" %>
  <body>
    <%= yield %>
  </body>
</html>